/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.graphics.forms;

import ec.edu.espe.graphics.forms.text.ComonText;
import ec.edu.espe.graphics.forms.text.ShapesCatalog;
import ec.edu.espe.math.geometry.shape.Shape;
import ec.edu.espe.math.geometry.shape.circumference.Circle;
import ec.edu.espe.math.geometry.shape.circumference.Ellipse;
import ec.edu.espe.util.GeometricConstants;
import ec.edu.espe.util.SupportUtil;
import javax.swing.JOptionPane;

/**
 *
 * @author alexander
 */
public class CircumferenceForms extends javax.swing.JFrame {

    /**
     * Creates new form CircumferenceForms
     */
    public CircumferenceForms() {
        initComponents();
        initializeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CirclePanel = new javax.swing.JPanel();
        lblRadius = new javax.swing.JLabel();
        btnCalculate = new javax.swing.JButton();
        lblArea = new javax.swing.JLabel();
        lblPerimeter = new javax.swing.JLabel();
        txtRadius = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        txtPerimeter = new javax.swing.JTextField();
        EllipsePanel = new javax.swing.JPanel();
        lblRadius2 = new javax.swing.JLabel();
        lblOtherRadius = new javax.swing.JLabel();
        btnCalculate2 = new javax.swing.JButton();
        lblArea2 = new javax.swing.JLabel();
        lblPerimeter2 = new javax.swing.JLabel();
        txtRadius2 = new javax.swing.JTextField();
        txtOtherRadius = new javax.swing.JTextField();
        txtArea2 = new javax.swing.JTextField();
        txtPerimeter2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnMainMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CirclePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblRadius.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRadius.setText("jLabel2");

        btnCalculate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalculate.setText("jButton1");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblArea.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArea.setText("jLabel4");

        lblPerimeter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPerimeter.setText("jLabel5");

        txtArea.setEnabled(false);

        txtPerimeter.setEnabled(false);

        javax.swing.GroupLayout CirclePanelLayout = new javax.swing.GroupLayout(CirclePanel);
        CirclePanel.setLayout(CirclePanelLayout);
        CirclePanelLayout.setHorizontalGroup(
            CirclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CirclePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CirclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CirclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblPerimeter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                    .addComponent(lblRadius, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(CirclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPerimeter, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(txtArea)
                    .addComponent(txtRadius))
                .addContainerGap())
        );
        CirclePanelLayout.setVerticalGroup(
            CirclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CirclePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CirclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRadius)
                    .addComponent(txtRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(btnCalculate)
                .addGap(18, 18, 18)
                .addGroup(CirclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CirclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerimeter)
                    .addComponent(txtPerimeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        EllipsePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblRadius2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRadius2.setText("jLabel2");

        lblOtherRadius.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOtherRadius.setText("jLabel3");

        btnCalculate2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalculate2.setText("jButton1");
        btnCalculate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate2ActionPerformed(evt);
            }
        });

        lblArea2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArea2.setText("jLabel4");

        lblPerimeter2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPerimeter2.setText("jLabel5");

        txtArea2.setEnabled(false);

        txtPerimeter2.setEnabled(false);

        javax.swing.GroupLayout EllipsePanelLayout = new javax.swing.GroupLayout(EllipsePanel);
        EllipsePanel.setLayout(EllipsePanelLayout);
        EllipsePanelLayout.setHorizontalGroup(
            EllipsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EllipsePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EllipsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EllipsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblPerimeter2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblArea2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalculate2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                    .addComponent(lblRadius2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOtherRadius, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(EllipsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPerimeter2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(txtArea2)
                    .addComponent(txtRadius2)
                    .addComponent(txtOtherRadius))
                .addContainerGap())
        );
        EllipsePanelLayout.setVerticalGroup(
            EllipsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EllipsePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EllipsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRadius2)
                    .addComponent(txtRadius2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EllipsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOtherRadius)
                    .addComponent(txtOtherRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(btnCalculate2)
                .addGap(18, 18, 18)
                .addGroup(EllipsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea2)
                    .addComponent(txtArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EllipsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerimeter2)
                    .addComponent(txtPerimeter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Circumference");

        btnMainMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMainMenu.setText("Main Menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CirclePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EllipsePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(224, 224, 224))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EllipsePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CirclePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        try{
        Shape circle=new Circle(Float.parseFloat(txtRadius.getText()));
        SupportUtil.showAreaPerimeter(circle, txtArea, txtPerimeter);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, ComonText.ERROR);
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnCalculate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate2ActionPerformed
        try{
        Shape ellipse=new Ellipse(Float.parseFloat(txtRadius2.getText()),Float.parseFloat(txtOtherRadius.getText()));
        SupportUtil.showAreaPerimeter(ellipse, txtArea2, txtPerimeter2);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, ComonText.ERROR);
        }
    }//GEN-LAST:event_btnCalculate2ActionPerformed

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        SupportUtil.openMainMenu(this);
    }//GEN-LAST:event_btnMainMenuActionPerformed
    private void initializeComponents(){
        CirclePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(ShapesCatalog.CIRCLE));
        EllipsePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(ShapesCatalog.ELLIPSE));
        lblArea.setText(GeometricConstants.AREA);lblPerimeter.setText(GeometricConstants.PERIMETER);
        lblArea2.setText(GeometricConstants.AREA);lblPerimeter2.setText(GeometricConstants.PERIMETER);
        lblRadius.setText(ComonText.RADIUS);lblOtherRadius.setText(ComonText.MIN_RADIUS);
        lblRadius2.setText(ComonText.RADIUS);
        btnCalculate.setText(ComonText.CALCULATE);
        btnCalculate2.setText(ComonText.CALCULATE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CircumferenceForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CircumferenceForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CircumferenceForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CircumferenceForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CircumferenceForms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CirclePanel;
    private javax.swing.JPanel EllipsePanel;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnCalculate2;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblArea2;
    private javax.swing.JLabel lblOtherRadius;
    private javax.swing.JLabel lblPerimeter;
    private javax.swing.JLabel lblPerimeter2;
    private javax.swing.JLabel lblRadius;
    private javax.swing.JLabel lblRadius2;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtArea2;
    private javax.swing.JTextField txtOtherRadius;
    private javax.swing.JTextField txtPerimeter;
    private javax.swing.JTextField txtPerimeter2;
    private javax.swing.JTextField txtRadius;
    private javax.swing.JTextField txtRadius2;
    // End of variables declaration//GEN-END:variables
}
