/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.graphics.forms;

import ec.edu.espe.graphics.forms.text.ComonText;
import ec.edu.espe.graphics.forms.text.ShapesCatalog;
import ec.edu.espe.math.geometry.shape.Shape;
import ec.edu.espe.math.geometry.shape.quadrilaterals.Parallelogram;
import ec.edu.espe.math.geometry.shape.quadrilaterals.Rectangle;
import ec.edu.espe.math.geometry.shape.quadrilaterals.Rhombus;
import ec.edu.espe.math.geometry.shape.quadrilaterals.Square;
import ec.edu.espe.math.geometry.shape.quadrilaterals.Trapezoid;
import ec.edu.espe.util.GeometricConstants;
import ec.edu.espe.util.SupportUtil;
import javax.swing.JOptionPane;

/**
 *
 * @author alexander
 */
public class QuadrilateralsForm extends javax.swing.JFrame {

    /**
     * Creates new form QuadrilateralsForm
     */
    public QuadrilateralsForm() {
        initComponents();
        initializeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SquarePanel = new javax.swing.JPanel();
        lblSide = new javax.swing.JLabel();
        txtSide = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        lblArea = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        txtPerimeter = new javax.swing.JTextField();
        lblPerimeter = new javax.swing.JLabel();
        RhombusPanel = new javax.swing.JPanel();
        lblMaxDiag = new javax.swing.JLabel();
        lblMinDiag = new javax.swing.JLabel();
        txtMaxDiag = new javax.swing.JTextField();
        txtMinDiag = new javax.swing.JTextField();
        btnCalculate3 = new javax.swing.JButton();
        lblArea3 = new javax.swing.JLabel();
        txtArea3 = new javax.swing.JTextField();
        lblPerimeter3 = new javax.swing.JLabel();
        txtPerimeter3 = new javax.swing.JTextField();
        ParalelogramPanel = new javax.swing.JPanel();
        lblHeight2 = new javax.swing.JLabel();
        lblSide2 = new javax.swing.JLabel();
        txtHeight2 = new javax.swing.JTextField();
        txtSide2 = new javax.swing.JTextField();
        btnCalculate4 = new javax.swing.JButton();
        lblArea4 = new javax.swing.JLabel();
        txtArea4 = new javax.swing.JTextField();
        lblPerimeter4 = new javax.swing.JLabel();
        txtPerimeter4 = new javax.swing.JTextField();
        lblWidth2 = new javax.swing.JLabel();
        txtWidth2 = new javax.swing.JTextField();
        TrapezoidPanel = new javax.swing.JPanel();
        lblMinBase = new javax.swing.JLabel();
        txtMinBase = new javax.swing.JTextField();
        lblMaxBase = new javax.swing.JLabel();
        txtMaxBase = new javax.swing.JTextField();
        btnCalculate5 = new javax.swing.JButton();
        lblArea5 = new javax.swing.JLabel();
        txtArea5 = new javax.swing.JTextField();
        lblPerimeter5 = new javax.swing.JLabel();
        txtPerimeter5 = new javax.swing.JTextField();
        lblHeight3 = new javax.swing.JLabel();
        txtHeight3 = new javax.swing.JTextField();
        RectanglePanel = new javax.swing.JPanel();
        lblWidth = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        txtWidth = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        btnCalculate2 = new javax.swing.JButton();
        lblArea2 = new javax.swing.JLabel();
        txtArea2 = new javax.swing.JTextField();
        lblPerimeter2 = new javax.swing.JLabel();
        txtPerimeter2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnMainMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 550));
        getContentPane().setLayout(null);

        SquarePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trapezoid", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblSide.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSide.setText("Side");

        btnCalculate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalculate.setText("jButton1");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblArea.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArea.setText("Area");

        txtArea.setEnabled(false);

        txtPerimeter.setEnabled(false);

        lblPerimeter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPerimeter.setText("Perimetro");

        javax.swing.GroupLayout SquarePanelLayout = new javax.swing.GroupLayout(SquarePanel);
        SquarePanel.setLayout(SquarePanelLayout);
        SquarePanelLayout.setHorizontalGroup(
            SquarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SquarePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SquarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SquarePanelLayout.createSequentialGroup()
                        .addComponent(lblSide, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSide, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SquarePanelLayout.createSequentialGroup()
                        .addComponent(lblPerimeter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(txtPerimeter, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SquarePanelLayout.createSequentialGroup()
                        .addGroup(SquarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblArea)
                            .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        SquarePanelLayout.setVerticalGroup(
            SquarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SquarePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SquarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSide)
                    .addComponent(txtSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnCalculate)
                .addGap(23, 23, 23)
                .addGroup(SquarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SquarePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerimeter)
                    .addComponent(txtPerimeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(SquarePanel);
        SquarePanel.setBounds(14, 49, 270, 199);

        RhombusPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trapezoid", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblMaxDiag.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMaxDiag.setText("Max Diag");

        lblMinDiag.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMinDiag.setText("Min Diag");

        btnCalculate3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalculate3.setText("jButton1");
        btnCalculate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate3ActionPerformed(evt);
            }
        });

        lblArea3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArea3.setText("jLabel4");

        txtArea3.setEnabled(false);

        lblPerimeter3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPerimeter3.setText("jLabel4");

        txtPerimeter3.setEnabled(false);

        javax.swing.GroupLayout RhombusPanelLayout = new javax.swing.GroupLayout(RhombusPanel);
        RhombusPanel.setLayout(RhombusPanelLayout);
        RhombusPanelLayout.setHorizontalGroup(
            RhombusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RhombusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RhombusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RhombusPanelLayout.createSequentialGroup()
                        .addGroup(RhombusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RhombusPanelLayout.createSequentialGroup()
                                .addGroup(RhombusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblPerimeter3, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(lblArea3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(RhombusPanelLayout.createSequentialGroup()
                                .addComponent(btnCalculate3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addGap(30, 30, 30)))
                        .addGroup(RhombusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtArea3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(txtPerimeter3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                    .addGroup(RhombusPanelLayout.createSequentialGroup()
                        .addGroup(RhombusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMinDiag, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaxDiag, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(RhombusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaxDiag)
                            .addComponent(txtMinDiag, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))))
                .addContainerGap())
        );
        RhombusPanelLayout.setVerticalGroup(
            RhombusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RhombusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RhombusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaxDiag)
                    .addComponent(txtMaxDiag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RhombusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMinDiag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinDiag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalculate3)
                .addGap(16, 16, 16)
                .addGroup(RhombusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea3)
                    .addComponent(txtArea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RhombusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerimeter3)
                    .addComponent(txtPerimeter3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(RhombusPanel);
        RhombusPanel.setBounds(640, 50, 280, 200);

        ParalelogramPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trapezoid", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblHeight2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHeight2.setText("Height");

        lblSide2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSide2.setText("Side");

        btnCalculate4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalculate4.setText("jButton1");
        btnCalculate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate4ActionPerformed(evt);
            }
        });

        lblArea4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArea4.setText("jLabel4");

        txtArea4.setEnabled(false);

        lblPerimeter4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPerimeter4.setText("jLabel4");

        txtPerimeter4.setEnabled(false);

        lblWidth2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblWidth2.setText("Width");

        txtWidth2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWidth2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ParalelogramPanelLayout = new javax.swing.GroupLayout(ParalelogramPanel);
        ParalelogramPanel.setLayout(ParalelogramPanelLayout);
        ParalelogramPanelLayout.setHorizontalGroup(
            ParalelogramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParalelogramPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ParalelogramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ParalelogramPanelLayout.createSequentialGroup()
                        .addComponent(lblPerimeter4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPerimeter4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ParalelogramPanelLayout.createSequentialGroup()
                        .addGroup(ParalelogramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalculate4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(txtArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ParalelogramPanelLayout.createSequentialGroup()
                        .addGroup(ParalelogramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeight2)
                            .addComponent(lblSide2)
                            .addComponent(lblWidth2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ParalelogramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtWidth2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(txtHeight2)
                            .addComponent(txtSide2))))
                .addContainerGap())
        );
        ParalelogramPanelLayout.setVerticalGroup(
            ParalelogramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParalelogramPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ParalelogramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeight2)
                    .addComponent(txtHeight2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ParalelogramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSide2)
                    .addComponent(txtSide2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ParalelogramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWidth2)
                    .addComponent(txtWidth2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnCalculate4)
                .addGap(18, 18, 18)
                .addGroup(ParalelogramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea4)
                    .addComponent(txtArea4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ParalelogramPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerimeter4)
                    .addComponent(txtPerimeter4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(ParalelogramPanel);
        ParalelogramPanel.setBounds(10, 266, 270, 222);

        TrapezoidPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trapezoid", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblMinBase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMinBase.setText("Min Base");

        lblMaxBase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMaxBase.setText("Max Base");

        btnCalculate5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalculate5.setText("jButton1");
        btnCalculate5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate5ActionPerformed(evt);
            }
        });

        lblArea5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArea5.setText("jLabel4");

        txtArea5.setEnabled(false);

        lblPerimeter5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPerimeter5.setText("jLabel4");

        txtPerimeter5.setEnabled(false);

        lblHeight3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHeight3.setText("Height");

        javax.swing.GroupLayout TrapezoidPanelLayout = new javax.swing.GroupLayout(TrapezoidPanel);
        TrapezoidPanel.setLayout(TrapezoidPanelLayout);
        TrapezoidPanelLayout.setHorizontalGroup(
            TrapezoidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrapezoidPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TrapezoidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TrapezoidPanelLayout.createSequentialGroup()
                        .addGroup(TrapezoidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCalculate5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TrapezoidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblPerimeter5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                .addComponent(lblArea5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(TrapezoidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtArea5, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(txtPerimeter5, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                    .addGroup(TrapezoidPanelLayout.createSequentialGroup()
                        .addGroup(TrapezoidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeight3)
                            .addComponent(lblMinBase)
                            .addComponent(lblMaxBase))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TrapezoidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaxBase, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(txtMinBase, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(txtHeight3))))
                .addGap(28, 28, 28))
        );
        TrapezoidPanelLayout.setVerticalGroup(
            TrapezoidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TrapezoidPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TrapezoidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeight3)
                    .addComponent(txtHeight3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TrapezoidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMinBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinBase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TrapezoidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaxBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaxBase))
                .addGap(18, 18, 18)
                .addComponent(btnCalculate5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(TrapezoidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea5)
                    .addComponent(txtArea5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(TrapezoidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerimeter5)
                    .addComponent(txtPerimeter5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(TrapezoidPanel);
        TrapezoidPanel.setBounds(330, 270, 280, 222);

        RectanglePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trapezoid", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblWidth.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblWidth.setText("Width");

        lblHeight.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHeight.setText("Height");

        btnCalculate2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalculate2.setText("jButton1");
        btnCalculate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate2ActionPerformed(evt);
            }
        });

        lblArea2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArea2.setText("Area");

        txtArea2.setEnabled(false);

        lblPerimeter2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPerimeter2.setText("Perimetro");

        txtPerimeter2.setEnabled(false);

        javax.swing.GroupLayout RectanglePanelLayout = new javax.swing.GroupLayout(RectanglePanel);
        RectanglePanel.setLayout(RectanglePanelLayout);
        RectanglePanelLayout.setHorizontalGroup(
            RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RectanglePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RectanglePanelLayout.createSequentialGroup()
                        .addGroup(RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtWidth)
                            .addComponent(txtHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RectanglePanelLayout.createSequentialGroup()
                        .addGroup(RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RectanglePanelLayout.createSequentialGroup()
                                .addGroup(RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblPerimeter2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblArea2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(RectanglePanelLayout.createSequentialGroup()
                                .addComponent(btnCalculate2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addGap(35, 35, 35)))
                        .addGroup(RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtArea2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(txtPerimeter2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))))
                .addContainerGap())
        );
        RectanglePanelLayout.setVerticalGroup(
            RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RectanglePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWidth)
                    .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeight)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalculate2)
                .addGap(23, 23, 23)
                .addGroup(RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArea2)
                    .addComponent(txtArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RectanglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerimeter2)
                    .addComponent(txtPerimeter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(RectanglePanel);
        RectanglePanel.setBounds(330, 50, 280, 199);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Quadrilaterals");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 10, 200, 30);

        btnMainMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMainMenu.setText("Main Menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMainMenu);
        btnMainMenu.setBounds(754, 445, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initializeComponents(){
        SquarePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(ShapesCatalog.SQUARE));
        RectanglePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(ShapesCatalog.RECTANGLE));
        RhombusPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(ShapesCatalog.RHOMBUS));
        ParalelogramPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(ShapesCatalog.PARALELOGRAM));
        TrapezoidPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(ShapesCatalog.TRAPEZOID));
        lblArea.setText(GeometricConstants.AREA);lblPerimeter.setText(GeometricConstants.PERIMETER);
        lblArea2.setText(GeometricConstants.AREA);lblPerimeter2.setText(GeometricConstants.PERIMETER);
        lblArea3.setText(GeometricConstants.AREA);lblPerimeter3.setText(GeometricConstants.PERIMETER);
        lblArea4.setText(GeometricConstants.AREA);lblPerimeter4.setText(GeometricConstants.PERIMETER);
        lblArea5.setText(GeometricConstants.AREA);lblPerimeter5.setText(GeometricConstants.PERIMETER);
        lblHeight.setText(ComonText.HEIGHT);lblWidth.setText(ComonText.WIDTH);lblSide.setText(ComonText.SIDE);
        lblHeight2.setText(ComonText.HEIGHT);lblWidth2.setText(ComonText.WIDTH);lblSide2.setText(ComonText.SIDE);
        lblHeight3.setText(ComonText.HEIGHT);
        lblMaxBase.setText(ComonText.MAX_BASE);lblMaxDiag.setText(ComonText.MAX_DIAG);
        lblMinBase.setText(ComonText.MIN_BASE);lblMinDiag.setText(ComonText.MIN_DIAG);
        btnCalculate.setText(ComonText.CALCULATE);
        btnCalculate2.setText(ComonText.CALCULATE);
        btnCalculate3.setText(ComonText.CALCULATE);
        btnCalculate4.setText(ComonText.CALCULATE);
        btnCalculate5.setText(ComonText.CALCULATE);
    }
    private void btnCalculate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate3ActionPerformed
        // Rhombus
        try{
        Shape rhombus=new Rhombus(Float.parseFloat(txtMaxDiag.getText()),Float.parseFloat(txtMinDiag.getText()));
        SupportUtil.showAreaPerimeter(rhombus, txtArea3, txtPerimeter3);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, ComonText.ERROR);
        }
    }//GEN-LAST:event_btnCalculate3ActionPerformed

    private void txtWidth2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWidth2ActionPerformed
        // BS:
    }//GEN-LAST:event_txtWidth2ActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // Square
        try{
        Shape square=new Square(Float.parseFloat(txtSide.getText()));
        SupportUtil.showAreaPerimeter(square, txtArea, txtPerimeter);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, ComonText.ERROR);
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnCalculate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate2ActionPerformed
        // Rectangle
        try{
        Shape rectangle=new Rectangle(Float.parseFloat(txtHeight.getText()),Float.parseFloat(txtWidth.getText()));
        SupportUtil.showAreaPerimeter(rectangle, txtArea2, txtPerimeter2);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, ComonText.ERROR);
        }
    }//GEN-LAST:event_btnCalculate2ActionPerformed

    private void btnCalculate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate4ActionPerformed
        // Paralelogram
        try{
        Shape parallelogram=new Parallelogram(Float.parseFloat(txtHeight2.getText()),Float.parseFloat(txtSide2.getText()),Float.parseFloat(txtWidth2.getText()));
        SupportUtil.showAreaPerimeter(parallelogram, txtArea4, txtPerimeter4);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, ComonText.ERROR);
        }
    }//GEN-LAST:event_btnCalculate4ActionPerformed

    private void btnCalculate5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate5ActionPerformed
        // Trapezoid,soon
        try{
        float minBase=Float.parseFloat(txtMinBase.getText());
        float maxBase=Float.parseFloat(txtMaxBase.getText());
        SupportUtil.MaxMinComparison(maxBase, minBase);
        Shape trapezoid=new Trapezoid(minBase,Float.parseFloat(txtHeight3.getText()),maxBase);
        SupportUtil.showAreaPerimeter(trapezoid, txtArea5, txtPerimeter5);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, ComonText.ERROR);
        }
    }//GEN-LAST:event_btnCalculate5ActionPerformed

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
        SupportUtil.openMainMenu(this);
    }//GEN-LAST:event_btnMainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuadrilateralsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuadrilateralsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuadrilateralsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuadrilateralsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuadrilateralsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ParalelogramPanel;
    private javax.swing.JPanel RectanglePanel;
    private javax.swing.JPanel RhombusPanel;
    private javax.swing.JPanel SquarePanel;
    private javax.swing.JPanel TrapezoidPanel;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnCalculate2;
    private javax.swing.JButton btnCalculate3;
    private javax.swing.JButton btnCalculate4;
    private javax.swing.JButton btnCalculate5;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblArea2;
    private javax.swing.JLabel lblArea3;
    private javax.swing.JLabel lblArea4;
    private javax.swing.JLabel lblArea5;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHeight2;
    private javax.swing.JLabel lblHeight3;
    private javax.swing.JLabel lblMaxBase;
    private javax.swing.JLabel lblMaxDiag;
    private javax.swing.JLabel lblMinBase;
    private javax.swing.JLabel lblMinDiag;
    private javax.swing.JLabel lblPerimeter;
    private javax.swing.JLabel lblPerimeter2;
    private javax.swing.JLabel lblPerimeter3;
    private javax.swing.JLabel lblPerimeter4;
    private javax.swing.JLabel lblPerimeter5;
    private javax.swing.JLabel lblSide;
    private javax.swing.JLabel lblSide2;
    private javax.swing.JLabel lblWidth;
    private javax.swing.JLabel lblWidth2;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtArea2;
    private javax.swing.JTextField txtArea3;
    private javax.swing.JTextField txtArea4;
    private javax.swing.JTextField txtArea5;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtHeight2;
    private javax.swing.JTextField txtHeight3;
    private javax.swing.JTextField txtMaxBase;
    private javax.swing.JTextField txtMaxDiag;
    private javax.swing.JTextField txtMinBase;
    private javax.swing.JTextField txtMinDiag;
    private javax.swing.JTextField txtPerimeter;
    private javax.swing.JTextField txtPerimeter2;
    private javax.swing.JTextField txtPerimeter3;
    private javax.swing.JTextField txtPerimeter4;
    private javax.swing.JTextField txtPerimeter5;
    private javax.swing.JTextField txtSide;
    private javax.swing.JTextField txtSide2;
    private javax.swing.JTextField txtWidth;
    private javax.swing.JTextField txtWidth2;
    // End of variables declaration//GEN-END:variables
}
