/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.graphics.forms;

import ec.edu.espe.graphics.forms.text.ComonText;
import ec.edu.espe.graphics.forms.text.ShapesCatalog;
import ec.edu.espe.math.geometry.shape.Shape;
import ec.edu.espe.math.geometry.shape.triangles.EquilateralTriangle;
import ec.edu.espe.math.geometry.shape.triangles.IsocelesTriangle;
import ec.edu.espe.math.geometry.shape.triangles.ObtuseAngleTriangle;
import ec.edu.espe.math.geometry.shape.triangles.RightAngleTriangle;
import ec.edu.espe.math.geometry.shape.triangles.ScaleneTriangle;
import ec.edu.espe.util.GeometricConstants;
import ec.edu.espe.util.SupportUtil;
import javax.swing.JOptionPane;

/**
 *
 * @author alexander
 */
public class TriangleForms extends javax.swing.JFrame {

    /**
     * Creates new form TriangleForms
     */
    public TriangleForms() {
        initComponents();
        initializeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EquilateralPanel = new javax.swing.JPanel();
        lblSide = new javax.swing.JLabel();
        txtSide = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        txtArea = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        lblPerimeter = new javax.swing.JLabel();
        txtPerimeter = new javax.swing.JTextField();
        IsocelesPanel = new javax.swing.JPanel();
        lblSide2 = new javax.swing.JLabel();
        lblBase = new javax.swing.JLabel();
        txtSide2 = new javax.swing.JTextField();
        txtBase = new javax.swing.JTextField();
        btnCalculate1 = new javax.swing.JButton();
        txtArea1 = new javax.swing.JTextField();
        lblArea1 = new javax.swing.JLabel();
        lblPerimeter1 = new javax.swing.JLabel();
        txtPerimeter1 = new javax.swing.JTextField();
        RightAnglePanel = new javax.swing.JPanel();
        lblHeight = new javax.swing.JLabel();
        lblBase2 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        txtBase2 = new javax.swing.JTextField();
        btnCalculate2 = new javax.swing.JButton();
        txtArea2 = new javax.swing.JTextField();
        lblArea2 = new javax.swing.JLabel();
        lblPerimeter2 = new javax.swing.JLabel();
        txtPerimeter2 = new javax.swing.JTextField();
        ObtuseAnglePanel = new javax.swing.JPanel();
        lblSide3 = new javax.swing.JLabel();
        lblHeight2 = new javax.swing.JLabel();
        lblBase3 = new javax.swing.JLabel();
        txtSide3 = new javax.swing.JTextField();
        txtHeight2 = new javax.swing.JTextField();
        txtBase3 = new javax.swing.JTextField();
        btnCalculate3 = new javax.swing.JButton();
        txtArea3 = new javax.swing.JTextField();
        lblArea3 = new javax.swing.JLabel();
        lblPerimeter3 = new javax.swing.JLabel();
        txtPerimeter3 = new javax.swing.JTextField();
        EscalenePanel = new javax.swing.JPanel();
        lblSideA = new javax.swing.JLabel();
        lblSideB = new javax.swing.JLabel();
        lblSideC = new javax.swing.JLabel();
        txtSideA = new javax.swing.JTextField();
        txtSideB = new javax.swing.JTextField();
        txtSideC = new javax.swing.JTextField();
        btnCalculate4 = new javax.swing.JButton();
        txtArea4 = new javax.swing.JTextField();
        lblArea4 = new javax.swing.JLabel();
        lblPerimeter4 = new javax.swing.JLabel();
        txtPerimeter4 = new javax.swing.JTextField();
        btnMainMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EquilateralPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblSide.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSide.setText("jLabel2");

        btnCalculate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalculate.setText("jButton1");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        txtArea.setEnabled(false);

        lblArea.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArea.setText("jLabel5");

        lblPerimeter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPerimeter.setText("jLabel6");

        txtPerimeter.setEnabled(false);

        javax.swing.GroupLayout EquilateralPanelLayout = new javax.swing.GroupLayout(EquilateralPanel);
        EquilateralPanel.setLayout(EquilateralPanelLayout);
        EquilateralPanelLayout.setHorizontalGroup(
            EquilateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EquilateralPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EquilateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EquilateralPanelLayout.createSequentialGroup()
                        .addComponent(lblSide, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(txtSide))
                    .addGroup(EquilateralPanelLayout.createSequentialGroup()
                        .addGroup(EquilateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EquilateralPanelLayout.createSequentialGroup()
                                .addComponent(btnCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addGap(51, 51, 51))
                            .addGroup(EquilateralPanelLayout.createSequentialGroup()
                                .addGroup(EquilateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPerimeter, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(EquilateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerimeter, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        EquilateralPanelLayout.setVerticalGroup(
            EquilateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EquilateralPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(EquilateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EquilateralPanelLayout.createSequentialGroup()
                        .addGroup(EquilateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSide)
                            .addComponent(txtSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addComponent(btnCalculate)
                        .addGap(29, 29, 29)
                        .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblArea))
                .addGap(18, 18, 18)
                .addGroup(EquilateralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerimeter)
                    .addComponent(txtPerimeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        IsocelesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblSide2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSide2.setText("jLabel2");

        lblBase.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBase.setText("jLabel3");

        btnCalculate1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalculate1.setText("jButton1");
        btnCalculate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate1ActionPerformed(evt);
            }
        });

        txtArea1.setEnabled(false);

        lblArea1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArea1.setText("jLabel5");

        lblPerimeter1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPerimeter1.setText("jLabel6");

        txtPerimeter1.setEnabled(false);

        javax.swing.GroupLayout IsocelesPanelLayout = new javax.swing.GroupLayout(IsocelesPanel);
        IsocelesPanel.setLayout(IsocelesPanelLayout);
        IsocelesPanelLayout.setHorizontalGroup(
            IsocelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IsocelesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IsocelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, IsocelesPanelLayout.createSequentialGroup()
                        .addGroup(IsocelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSide2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(IsocelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSide2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBase, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(IsocelesPanelLayout.createSequentialGroup()
                        .addGroup(IsocelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IsocelesPanelLayout.createSequentialGroup()
                                .addComponent(btnCalculate1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addGap(51, 51, 51))
                            .addGroup(IsocelesPanelLayout.createSequentialGroup()
                                .addGroup(IsocelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPerimeter1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(IsocelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerimeter1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        IsocelesPanelLayout.setVerticalGroup(
            IsocelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IsocelesPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(IsocelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IsocelesPanelLayout.createSequentialGroup()
                        .addComponent(txtSide2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IsocelesPanelLayout.createSequentialGroup()
                        .addComponent(lblSide2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBase)))
                .addGap(37, 37, 37)
                .addGroup(IsocelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IsocelesPanelLayout.createSequentialGroup()
                        .addComponent(btnCalculate1)
                        .addGap(29, 29, 29)
                        .addComponent(txtArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblArea1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(IsocelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerimeter1)
                    .addComponent(txtPerimeter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        RightAnglePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblHeight.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHeight.setText("jLabel2");

        lblBase2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBase2.setText("jLabel3");

        btnCalculate2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalculate2.setText("jButton1");
        btnCalculate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate2ActionPerformed(evt);
            }
        });

        txtArea2.setEnabled(false);

        lblArea2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArea2.setText("jLabel5");

        lblPerimeter2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPerimeter2.setText("jLabel6");

        txtPerimeter2.setEnabled(false);

        javax.swing.GroupLayout RightAnglePanelLayout = new javax.swing.GroupLayout(RightAnglePanel);
        RightAnglePanel.setLayout(RightAnglePanelLayout);
        RightAnglePanelLayout.setHorizontalGroup(
            RightAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightAnglePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RightAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RightAnglePanelLayout.createSequentialGroup()
                        .addGroup(RightAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBase2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHeight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(RightAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHeight, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBase2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(RightAnglePanelLayout.createSequentialGroup()
                        .addGroup(RightAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RightAnglePanelLayout.createSequentialGroup()
                                .addComponent(btnCalculate2, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addGap(51, 51, 51))
                            .addGroup(RightAnglePanelLayout.createSequentialGroup()
                                .addGroup(RightAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPerimeter2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(RightAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerimeter2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        RightAnglePanelLayout.setVerticalGroup(
            RightAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightAnglePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(RightAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightAnglePanelLayout.createSequentialGroup()
                        .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBase2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RightAnglePanelLayout.createSequentialGroup()
                        .addComponent(lblHeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBase2)))
                .addGap(37, 37, 37)
                .addGroup(RightAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightAnglePanelLayout.createSequentialGroup()
                        .addComponent(btnCalculate2)
                        .addGap(29, 29, 29)
                        .addComponent(txtArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblArea2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(RightAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerimeter2)
                    .addComponent(txtPerimeter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ObtuseAnglePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblSide3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSide3.setText("jLabel2");

        lblHeight2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHeight2.setText("jLabel3");

        lblBase3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBase3.setText("jLabel4");

        btnCalculate3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalculate3.setText("jButton1");
        btnCalculate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate3ActionPerformed(evt);
            }
        });

        txtArea3.setEnabled(false);

        lblArea3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArea3.setText("jLabel5");

        lblPerimeter3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPerimeter3.setText("jLabel6");

        txtPerimeter3.setEnabled(false);

        javax.swing.GroupLayout ObtuseAnglePanelLayout = new javax.swing.GroupLayout(ObtuseAnglePanel);
        ObtuseAnglePanel.setLayout(ObtuseAnglePanelLayout);
        ObtuseAnglePanelLayout.setHorizontalGroup(
            ObtuseAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ObtuseAnglePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ObtuseAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ObtuseAnglePanelLayout.createSequentialGroup()
                        .addGroup(ObtuseAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSide3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(lblHeight2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBase3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(ObtuseAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSide3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHeight2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBase3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(ObtuseAnglePanelLayout.createSequentialGroup()
                        .addGroup(ObtuseAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ObtuseAnglePanelLayout.createSequentialGroup()
                                .addComponent(btnCalculate3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(51, 51, 51))
                            .addGroup(ObtuseAnglePanelLayout.createSequentialGroup()
                                .addGroup(ObtuseAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPerimeter3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(ObtuseAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerimeter3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        ObtuseAnglePanelLayout.setVerticalGroup(
            ObtuseAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ObtuseAnglePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(ObtuseAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ObtuseAnglePanelLayout.createSequentialGroup()
                        .addComponent(txtSide3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHeight2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBase3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ObtuseAnglePanelLayout.createSequentialGroup()
                        .addComponent(lblSide3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHeight2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBase3)
                        .addGap(10, 10, 10)))
                .addGroup(ObtuseAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ObtuseAnglePanelLayout.createSequentialGroup()
                        .addComponent(btnCalculate3)
                        .addGap(29, 29, 29)
                        .addComponent(txtArea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblArea3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(ObtuseAnglePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerimeter3)
                    .addComponent(txtPerimeter3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        EscalenePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lblSideA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSideA.setText("jLabel2");

        lblSideB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSideB.setText("jLabel3");

        lblSideC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSideC.setText("jLabel4");

        btnCalculate4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalculate4.setText("jButton1");
        btnCalculate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculate4ActionPerformed(evt);
            }
        });

        txtArea4.setEnabled(false);

        lblArea4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblArea4.setText("jLabel5");

        lblPerimeter4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPerimeter4.setText("jLabel6");

        txtPerimeter4.setEnabled(false);

        javax.swing.GroupLayout EscalenePanelLayout = new javax.swing.GroupLayout(EscalenePanel);
        EscalenePanel.setLayout(EscalenePanelLayout);
        EscalenePanelLayout.setHorizontalGroup(
            EscalenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscalenePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EscalenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EscalenePanelLayout.createSequentialGroup()
                        .addGroup(EscalenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSideC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSideB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSideA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(EscalenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSideA, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSideB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSideC, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(EscalenePanelLayout.createSequentialGroup()
                        .addGroup(EscalenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EscalenePanelLayout.createSequentialGroup()
                                .addComponent(btnCalculate4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(51, 51, 51))
                            .addGroup(EscalenePanelLayout.createSequentialGroup()
                                .addGroup(EscalenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPerimeter4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(EscalenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerimeter4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        EscalenePanelLayout.setVerticalGroup(
            EscalenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscalenePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(EscalenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EscalenePanelLayout.createSequentialGroup()
                        .addComponent(txtSideA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSideB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSideC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscalenePanelLayout.createSequentialGroup()
                        .addComponent(lblSideA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSideB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSideC)
                        .addGap(9, 9, 9)))
                .addGroup(EscalenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EscalenePanelLayout.createSequentialGroup()
                        .addComponent(btnCalculate4)
                        .addGap(29, 29, 29)
                        .addComponent(txtArea4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblArea4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(EscalenePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPerimeter4)
                    .addComponent(txtPerimeter4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMainMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMainMenu.setText("Main Menu");
        btnMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainMenuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Triangles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EquilateralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ObtuseAnglePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EscalenePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IsocelesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RightAnglePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EquilateralPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IsocelesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RightAnglePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ObtuseAnglePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(EscalenePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        //Equilateral
        try{
        Shape equilateral=new EquilateralTriangle(Float.parseFloat(txtSide.getText()));
        SupportUtil.showAreaPerimeter(equilateral, txtArea, txtPerimeter);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, ComonText.ERROR);
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnCalculate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate1ActionPerformed
        // Isoceles
        try{
        float side2=Float.parseFloat(txtSide2.getText());
        float base=Float.parseFloat(txtBase.getText());
        SupportUtil.MaxMinComparison(side2*2, base);
        Shape isoceles=new IsocelesTriangle(side2,base);
        SupportUtil.showAreaPerimeter(isoceles, txtArea1, txtPerimeter1);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, ComonText.ERROR);
        }
    }//GEN-LAST:event_btnCalculate1ActionPerformed

    private void btnCalculate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate2ActionPerformed
        // Right Angle
        try{
        Shape rightangle=new RightAngleTriangle(Float.parseFloat(txtBase2.getText()),Float.parseFloat(txtHeight.getText()));
        SupportUtil.showAreaPerimeter(rightangle, txtArea2, txtPerimeter2);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, ComonText.ERROR);
        }
    }//GEN-LAST:event_btnCalculate2ActionPerformed

    private void btnCalculate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate3ActionPerformed
        // Obtuse Angle
        try{
        float side3=Float.parseFloat(txtSide3.getText());
        float height2=Float.parseFloat(txtHeight2.getText());
        SupportUtil.MaxMinComparison(side3, height2);
        Shape obtuseangle=new ObtuseAngleTriangle(side3,Float.parseFloat(txtBase3.getText()),height2);
        SupportUtil.showAreaPerimeter(obtuseangle, txtArea3, txtPerimeter3);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, ComonText.ERROR);
        }
    }//GEN-LAST:event_btnCalculate3ActionPerformed

    private void btnCalculate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculate4ActionPerformed
        // scalene
        try{
        float sideA=Float.parseFloat(txtSideA.getText());
        float sideB=Float.parseFloat(txtSideB.getText());
        float sideC=Float.parseFloat(txtSideC.getText());
        SupportUtil.MaxMinComparison(sideA+sideB, sideC);
        SupportUtil.MaxMinComparison(sideA+sideC, sideB);
        SupportUtil.MaxMinComparison(sideC+sideB, sideA);
        Shape escalene=new ScaleneTriangle(Float.parseFloat(txtSideA.getText()),Float.parseFloat(txtSideB.getText()),Float.parseFloat(txtSideC.getText()), 0);
        SupportUtil.showAreaPerimeter(escalene, txtArea4, txtPerimeter4);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, ComonText.ERROR);
        }
    }//GEN-LAST:event_btnCalculate4ActionPerformed

    private void btnMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainMenuActionPerformed
       SupportUtil.openMainMenu(this);
    }//GEN-LAST:event_btnMainMenuActionPerformed
    private void initializeComponents(){
        EquilateralPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(ShapesCatalog.EQUILATERAL_TRIANGLE));
        IsocelesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(ShapesCatalog.ISOCELES_TRIANGLE));
        RightAnglePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(ShapesCatalog.RIGHT_ANGLE_TRIANGLE));
        ObtuseAnglePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(ShapesCatalog.OBTUSE_ANGLE_TRIANGLE));
        EscalenePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(ShapesCatalog.ESCALENE_TRIANGLE));
        lblArea.setText(GeometricConstants.AREA);lblPerimeter.setText(GeometricConstants.PERIMETER);
        lblArea1.setText(GeometricConstants.AREA);lblPerimeter1.setText(GeometricConstants.PERIMETER);
        lblArea2.setText(GeometricConstants.AREA);lblPerimeter2.setText(GeometricConstants.PERIMETER);
        lblArea3.setText(GeometricConstants.AREA);lblPerimeter3.setText(GeometricConstants.PERIMETER);
        lblArea4.setText(GeometricConstants.AREA);lblPerimeter4.setText(GeometricConstants.PERIMETER);
        lblBase.setText(ComonText.BASE);lblSide.setText(ComonText.SIDE);
        lblBase2.setText(ComonText.BASE);lblSide2.setText(ComonText.SIDE);
        lblBase3.setText(ComonText.BASE);lblSide3.setText(ComonText.SIDE);
        lblHeight.setText(ComonText.HEIGHT);lblHeight2.setText(ComonText.HEIGHT);
        lblSideA.setText(ComonText.SIDE+" A");lblSideB.setText(ComonText.SIDE+" B");lblSideC.setText(ComonText.SIDE+" C");
        btnCalculate.setText(ComonText.CALCULATE);
        btnCalculate1.setText(ComonText.CALCULATE);
        btnCalculate2.setText(ComonText.CALCULATE);
        btnCalculate3.setText(ComonText.CALCULATE);
        btnCalculate4.setText(ComonText.CALCULATE);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TriangleForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TriangleForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TriangleForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TriangleForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TriangleForms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EquilateralPanel;
    private javax.swing.JPanel EscalenePanel;
    private javax.swing.JPanel IsocelesPanel;
    private javax.swing.JPanel ObtuseAnglePanel;
    private javax.swing.JPanel RightAnglePanel;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnCalculate1;
    private javax.swing.JButton btnCalculate2;
    private javax.swing.JButton btnCalculate3;
    private javax.swing.JButton btnCalculate4;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblArea1;
    private javax.swing.JLabel lblArea2;
    private javax.swing.JLabel lblArea3;
    private javax.swing.JLabel lblArea4;
    private javax.swing.JLabel lblBase;
    private javax.swing.JLabel lblBase2;
    private javax.swing.JLabel lblBase3;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHeight2;
    private javax.swing.JLabel lblPerimeter;
    private javax.swing.JLabel lblPerimeter1;
    private javax.swing.JLabel lblPerimeter2;
    private javax.swing.JLabel lblPerimeter3;
    private javax.swing.JLabel lblPerimeter4;
    private javax.swing.JLabel lblSide;
    private javax.swing.JLabel lblSide2;
    private javax.swing.JLabel lblSide3;
    private javax.swing.JLabel lblSideA;
    private javax.swing.JLabel lblSideB;
    private javax.swing.JLabel lblSideC;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtArea1;
    private javax.swing.JTextField txtArea2;
    private javax.swing.JTextField txtArea3;
    private javax.swing.JTextField txtArea4;
    private javax.swing.JTextField txtBase;
    private javax.swing.JTextField txtBase2;
    private javax.swing.JTextField txtBase3;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtHeight2;
    private javax.swing.JTextField txtPerimeter;
    private javax.swing.JTextField txtPerimeter1;
    private javax.swing.JTextField txtPerimeter2;
    private javax.swing.JTextField txtPerimeter3;
    private javax.swing.JTextField txtPerimeter4;
    private javax.swing.JTextField txtSide;
    private javax.swing.JTextField txtSide2;
    private javax.swing.JTextField txtSide3;
    private javax.swing.JTextField txtSideA;
    private javax.swing.JTextField txtSideB;
    private javax.swing.JTextField txtSideC;
    // End of variables declaration//GEN-END:variables
}
